# PostgreSQL. Versions 7.4 and 8.x are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
# development:
#     adapter: postgresql
#     host: localhost
#     port: 5432
#     username: postgres
#     password: kenrome
#     database: laopo
#     schema_search_path: public
#     encoding: unicode

base: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: kenrome001
  host: 127.0.0.1
  port: 3303

development:
  <<: *base
  database: dream2

test:
  <<: *base
  database: dream2

production:
  <<: *base
  database: dream2